/* automatically generated by rust-bindgen */

pub type int8_t = ::ty::c_char;
pub type int16_t = ::ty::c_short;
pub type int32_t = ::ty::c_int;
pub type int64_t = ::ty::c_long;
pub type uint8_t = ::ty::c_uchar;
pub type uint16_t = ::ty::c_ushort;
pub type uint32_t = ::ty::c_uint;
pub type uint64_t = ::ty::c_ulong;
pub type int_least8_t = ::ty::c_char;
pub type int_least16_t = ::ty::c_short;
pub type int_least32_t = ::ty::c_int;
pub type int_least64_t = ::ty::c_long;
pub type uint_least8_t = ::ty::c_uchar;
pub type uint_least16_t = ::ty::c_ushort;
pub type uint_least32_t = ::ty::c_uint;
pub type uint_least64_t = ::ty::c_ulong;
pub type int_fast8_t = ::ty::c_char;
pub type int_fast16_t = ::ty::c_long;
pub type int_fast32_t = ::ty::c_long;
pub type int_fast64_t = ::ty::c_long;
pub type uint_fast8_t = ::ty::c_uchar;
pub type uint_fast16_t = ::ty::c_ulong;
pub type uint_fast32_t = ::ty::c_ulong;
pub type uint_fast64_t = ::ty::c_ulong;
pub type intptr_t = ::ty::c_long;
pub type uintptr_t = ::ty::c_ulong;
pub type intmax_t = ::ty::c_long;
pub type uintmax_t = ::ty::c_ulong;
extern "C" {
    pub fn HAL_Delay_Milliseconds(millis: uint32_t);
    pub fn HAL_Delay_Microseconds(micros: uint32_t);
}
